Install Python Imaging Library
The scoring script requires the Python Imaging Library. Without it, running the
script results in the following error:

    Traceback (most recent call last):
      File "/covalic/Python/scoreSubmission.py", line 12, in <module>
	from PIL import Image
    ImportError: No module named PIL